### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by FSaurenbach** [SchneckeddeF/leaping-light#3]
- [x] #5
- [x] UFO
- [x] Popup in the shop when the money is insufficient
- [x] Better reviving
- [ ] Save skins
- [ ] More clearing of objects while reviving
- [ ] Pause button with a corresponding menu
- [ ] If clicked on the back button in the credits scene you should get to the options scene and not the Main Menu.
- [ ] Fullscreen on android (stretching)
- [ ] More items in the shop likebackgrounds and more skins (and special offers)
- [ ] Ads with admob
- [ ] Add new sounds and music to the gamplay
- [ ] Loop the music somehow better so it sounds better when the song ends.
